apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: food-delivery-eks
  region: ap-south-1
  version: "1.29"

vpc:
  id: vpc-0858ff4b7786081fe
  subnets:
    private:
      ap-south-1a:
        id: subnet-08fc7b3dfa7148607
      ap-south-1b:
        id: subnet-090e7f1e5e845bb07
      ap-south-1c:
        id: subnet-01649ec3a86075c4e
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

managedNodeGroups:
  - name: ondemand-ng
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    privateNetworking: true
    labels:
      node-type: ondemand
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/food-delivery-eks: "owned"

  - name: spot-ng
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    spot: true
    privateNetworking: true
    labels:
      node-type: spot
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/food-delivery-eks: "owned"