apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - ondemand
      containers:
        - name: cart-service
          image: "{{ .Values.images.cartService.repository }}:{{ .Values.images.cartService.tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
{{- toYaml .Values.resources | nindent 12 }}
