apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: food-app
spec:
  type: ClusterIP
  selector:
    app: restaurant-service
  ports:
    - port: 8081
      targetPort: 8081
